let diff = {};

let a = {
  id: 3,
  deviceIp: "192.168.1.238",
  dnsServerIP: ["192.168.1.1"],
  gatewayIP: ["192.168.1.1"],
  broadcastIP: "192.168.1.255",
  subnetMask: "255.255.255.0",
  determiner: false,
  vlanId: -1,
  dhcpClientName: "hpenvyprinter1",
  mac: "70:5a:0f:e4:9b:c0",
  switchMac: "14:cc:20:51:33:ea",
  createdTimestamp: 1660557003000,
  lastSeenTimestamp: 1666226656000,
  lifecycleState: "IOT_TYPE_CLASSIFIED",
  deviceTypeId: 14,
  deviceCategory: "IOT",
  observedMac: "70:5a:0f:e4:9b:c0",
  attributes: [
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DEVICE_IP",
      attributeValue: "192.168.1.238",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DNS_SERVERS",
      attributeValue: "192.168.1.1",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "GATEWAY_IPS",
      attributeValue: "192.168.1.1",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "BROADCAST_IP",
      attributeValue: "192.168.1.255",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "SUBNET_MASK",
      attributeValue: "255.255.255.0",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DETERMINER",
      attributeValue: false,
      attributeType: "BOOLEAN",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "VLAN_ID",
      attributeValue: -1,
      attributeType: "INTEGER",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DHCP_CLIENT_NAME",
      attributeValue: "hpenvyprinter1",
      attributeType: "STRING",
    },
  ],
};

let b = {
  id: 3,
  deviceIp: "192.168.1.238",
  dnsServerIP: ["192.168.1.1"],
  gatewayIP: ["192.168.1.1"],
  broadcastIP: "192.168.1.255",
  subnetMask: "255.255.255.0",
  determiner: false,
  vlanId: -1,
  dhcpClientName: "hpenvyprinter1",
  mac: "70:5a:0f:e4:9b:c0",
  switchMac: "14:cc:20:51:33:ea",
  createdTimestamp: 1660557003000,
  lastSeenTimestamp: 1666227908000,
  lifecycleState: "IOT_TYPE_CLASSIFIED",
  deviceTypeId: 14,
  deviceCategory: "IOT",
  observedMac: "70:5a:0f:e4:9b:c0",
  deviceType: "Hewlett Packard New Type",
  model: "HP ENVY 5540 series",
  ouiManufacturer: "HP",
  deviceServices:
    "SMTP,EPMAP,HTTPS,SNMP,DHCPV6-CLIENT,SSDP,NETBIOS-NS,pdl-datastream,SIP,mDNS,DHCP",
  remoteServices: "DHCPV6-SERVER,HTTPS,DNS,mDNS,DHCP",
  fqdn: "hpenvyprinter1.lan",
  attributes: [
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DEVICE_IP",
      attributeValue: "192.168.1.238",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DNS_SERVERS",
      attributeValue: "192.168.1.1",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "GATEWAY_IPS",
      attributeValue: "192.168.1.1",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "BROADCAST_IP",
      attributeValue: "192.168.1.255",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "SUBNET_MASK",
      attributeValue: "255.255.255.0",
      attributeType: "STRING",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DETERMINER",
      attributeValue: false,
      attributeType: "BOOLEAN",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "VLAN_ID",
      attributeValue: -1,
      attributeType: "INTEGER",
    },
    {
      createdTimestamp: 0,
      updatedTimestamp: 0,
      deviceId: 3,
      flowName: "device",
      attributeName: "DHCP_CLIENT_NAME",
      attributeValue: "hpenvyprinter1",
      attributeType: "STRING",
    },
  ],
};

for (const [key, value] of Object.entries(b)) {
  if (a[key] && a[key] === value) continue;
  diff[key] = {};
  diff[key].a = a[key];
  diff[key].b = value;
}

console.table(diff);
